/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.springframework.context.annotation.AnnotationConfigApplicationContext;

public class App {

    public static void main(String[] args) {
        new AnnotationConfigApplicationContext("org.example.beans");
    }
}

